// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System',
      items: [
        'module-1/index',
        'module-1/robotic-middleware-fundamentals',
        'module-1/core-communication-concepts',
        'module-1/ai-agents-robot-models',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Robot Kinematics & Physical Structure',
      items: [
        'module-2/index',
        'module-2/links-joints-coordinate-frames',
        'module-2/forward-inverse-kinematics',
        'module-2/joint-constraints-motion-limits',
        'module-2/urdf-mapping-real-simulated',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The Digital Twin',
      items: [
        'module-3/index',
        'module-3/gazebo-simulation-setup',
        'module-3/physics-collision-modeling',
        'module-3/navigation-motion-planning',
        'module-3/unity-visualization',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Perception Systems for Robots',
      items: [
        'module-4/index',
        'module-4/robot-camera-models',  // Contains Robot Camera Models (RGB, Depth, Stereo)
        'module-4/lidar-fundamentals',   // Contains LiDAR Fundamentals for Robotics
        'module-4/imu-sensor-fusion', // Contains IMU Data and Sensor Fusion
        'module-4/building-perception-pipelines', // Contains Building Perception Pipelines in ROS 2
      ],
    },
    {
      type: 'category',
      label: 'Module 5: The AI-Robot Brain (NVIDIA Isaac)',
      items: [
        'module-5/index',
        'module-5/isaac-sim-overview-architecture',
        'module-5/synthetic-data-generation',
        'module-5/isaac-ros-hardware-accelerated-vslam',
        'module-5/nav2-path-planning-humanoid-mobile-robots',
      ],
    },
    {
      type: 'category',
      label: 'Module 6: Vision–Language–Action (VLA)',
      items: [
        'module-6/index',
        'module-6/vla-fundamentals',
        'module-6/voice-to-action',
        'module-6/cognitive-planning',
        'module-6/executing-language-plans',
      ],
    },
    // Add more modules as needed
  ],
};

export default sidebars;
